name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo `date` > world.txt
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-0
        path: world.txt
    
    # This is a small zip file, but a 1MB file inside it.
    - run: dd if=/dev/zero of=small-zip.txt count=1024 bs=1024
      
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-2
        path: small-zip.txt
  
    # This is a 1MB zip file, and 1MB file inside it.
    - run: dd if=/dev/urandom of=large-zip.txt count=1024 bs=1024
      
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-3
        path: larger-zip.txt
    
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-4
        path: world.txt
    
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-5
        path: world.txt
    
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-6
        path: world.txt
    
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-7
        path: world.txt
    
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-8
        path: world.txt
    
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact-9
        path: world.txt
 
